### ISSUE TITLE
Watchdog.sleep() and Feather Lora M0

### ISSUE THREAD

**Issue by lbovay** [adafruit/Adafruit_SleepyDog#7]
Hi,
did anyone get Watchdog.sleep(xxxx) to work with the Feather Lora M0 ?
Mine goes to sleep but never wakes up :(

I use the Sleep example code.

Cheers,

**Comment by PaintYourDragon** [comment]
Code's there and works, but just noticed I didn't bump the version number, so Arduino IDE might not pick up the latest. I'll do that in a couple minutes here (to version 1.1.1), but may take some time to filter up...can either wait a little while, or download and install ZIP if needed immediately.

**Comment by lbovay** [comment]
Thank you for your answer,

Still no luck with the Sleep example. I'm running Arduino 1.8.1, I installed this library in V1.1.1 aswell as this dependancy: https://github.com/adafruit/Adafruit_ASFcore

Code is building without issues, console output is:
`Adafruit Watchdog Library Sleep Demo!

Going to sleep in one second...
`

**Comment by PaintYourDragon** [comment]
Not sure what to suggest. I'm running same version of IDE & libraries. Slightly different board (RFM69 instead of LoRa), but that shouldn't make a difference, all the M0 boards should run that code identically. MAYBE a compiler difference (I'm on Mac) but haven't seen that sort of thing in years.

**Comment by scott2b** [comment]
Re: the LoRa boards. If you are using RadioHead, iirc there is a conflict between the radio driver and Sleepy Dog. I believe it was the case when I tried it that they were competing for the same interrupt or something like that. Otherwise, if not using the RadioHead driver for the LoRa, Sleepy Dog seems to work fine.

One caveat. I might not look like it is waking up if you are depending on Serial output. It will lose the serial connection when it goes to sleep. Also, re-loading can be quite finicky if you have a sleep in your loop. I find that I have to kick the Feather by pushing the reset button 2x in order to load new code.

**Comment by huzarif97** [comment]
I am currently trying to use both RadioHead and Sleepy Dog and am experiencing the issue scott2b is describing; I found a quick fix where I comment out the area of tc_interrupts.c that creates the TCx_Handler for each TC, but I would like to find a better way that salvages all of the TC's in case I need them for the future.  Thanks

**Comment by Kuurusch** [comment]
Hey, is this issue fixed for the LoRa-modul on the M0?

**Comment by Kuurusch** [comment]
Had someone luck with the radioHead and SleepyDog?

**Comment by loicgillioz** [comment]
Hi, i've effectively found that going into sleep mode with the LoRa module used makes it crash. I will keep you updated if I find a fix.

**Comment by Kuurusch** [comment]
@loicgillioz Hey, thanks a lot, yea would be cool. Otherwise the M0 needs way too much energy :/

**Comment by nyfelix** [comment]
Thank you guys, after testing for almost an hour I realised, that after sleep the Serial connection was broken... but it works all fine.
